services:
  - name: users-api
    image: users-api:latest
    port: 8080
    healthcheck: /health
    volumes:
      - ./data:/app/data
    networks:
      - dockpilot-net
    ports:
      - 8080:8080
